### PR TITLE
CODENVY-1814: Rework project syncing to fix compatibility issue

### LINKED ISSUE #1814: Can't backup/restore workspaces because of old rsync version
Got this errors:
```
2017-02-21 00:33:34,539[ceSharedPool-12]  [ERROR] [DockerEnvironmentBackupManager 509]  - Error occurred during backup/restore of workspace 'workspace*************' on node 'node7.codenvy.io' : Warning: Permanently added '[node7.codenv
rsync: on remote machine: --usermap=*:1000: unknown option
rsync error: syntax or usage error (code 1) at main.c(1435) [server=3.0.9]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
2017-02-21 00:33:34,540[ceSharedPool-12]  [ERROR] [DockerEnvironmentBackupManager 319]  - Synchronization process failed. Exit code 12
java.io.IOException: Synchronization process failed. Exit code 12
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:511) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreBackupInsideLock(DockerEnvironmentBackupManager.java:308) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreWorkspaceBackup(DockerEnvironmentBackupManager.java:194) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:94) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.agent.launcher.MachineInnerRsyncAgentLauncherImpl.launch(MachineInnerRsyncAgentLauncherImpl.java:68) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:695) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:816) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:267) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) [che-core-commons-lang-5.3.0.jar:5.3.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
```
This is because of old version of `rsync`, probably on old debian
Need to find way to work even on old debian or print message to user explaining why we can't start workspace.

Also please include more info in error message for second error, it probably related to previous one because of time difference is so small, but need to be sure.
So please include at least workspace ID in error message.

**Codenvy version:**    5.3.0

**OS and version:**    Centos 7.2

**Docker version:** 1.12.5

### LINKED ISSUE #1820: Exceptions when rsync-ing projeccts with symlinks
Every backup or restore of workspace with symlinks produce errors in log like:
```
2017-02-21 16:23:05,031[aceSharedPool-1]  [ERROR] [DockerEnvironmentBackupManager 509]  - Error occurred during backup/restore of workspace 'workspacenbnl8c5zy6e3o7kv' on node 'node2.c5.codenvy-stg.com' : rsync: failed to set permissions on "/opt/codenvy-data/fs/f5/50/56/workspacenbnl8c5zy6e3o7kv/symlins-test/file-symlink": Not supported (95)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1650) [generator=3.1.2]
2017-02-21 16:23:05,044[aceSharedPool-1]  [ERROR] [DockerEnvironmentBackupManager 356]  - Synchronization process failed. Exit code 23
java.io.IOException: Synchronization process failed. Exit code 23
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:511) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:347) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupAndCleanupInsideLock(DockerEnvironmentBackupManager.java:260) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspaceAndCleanup(DockerEnvironmentBackupManager.java:159) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.RemoteDockerNode.unbindWorkspace(RemoteDockerNode.java:107) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:268) [che-plugin-docker-machine-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyMachine(CheEnvironmentEngine.java:1174) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyEnvironment(CheEnvironmentEngine.java:1151) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.stop(CheEnvironmentEngine.java:331) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stopEnvironmentAndPublishEvents(WorkspaceRuntimes.java:802) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:370) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$stopAsync$3(WorkspaceManager.java:826) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.3.0.jar:5.3.0]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
2017-02-21 16:23:05,045[aceSharedPool-1]  [ERROR] [c.c.machine.RemoteDockerNode 110]    - Backup of workspace workspacenbnl8c5zy6e3o7kv filesystem terminated on node2.c5.codenvy-stg.com node. Synchronization process failed. Exit code 23
org.eclipse.che.api.core.ServerException: Backup of workspace workspacenbnl8c5zy6e3o7kv filesystem terminated on node2.c5.codenvy-stg.com node. Synchronization process failed. Exit code 23
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:359) ~[codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupAndCleanupInsideLock(DockerEnvironmentBackupManager.java:260) ~[codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspaceAndCleanup(DockerEnvironmentBackupManager.java:159) ~[codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.RemoteDockerNode.unbindWorkspace(RemoteDockerNode.java:107) ~[codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:268) [che-plugin-docker-machine-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyMachine(CheEnvironmentEngine.java:1174) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyEnvironment(CheEnvironmentEngine.java:1151) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.stop(CheEnvironmentEngine.java:331) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stopEnvironmentAndPublishEvents(WorkspaceRuntimes.java:802) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:370) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$stopAsync$3(WorkspaceManager.java:826) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.3.0.jar:5.3.0]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
```
We need to tweak options for `rsync` because it imposible set permissions for symlink, it's inherited from original file.
There is no real problem with backup/restore, that messages just pollutes log.

**Reproduction Steps:**
- Open terminal tab
- `mkdir symlins-test`
- `cd symlins-test/`
- `echo "ffff" > file-original`
- `ln -s file-original file-symlink`
- Observe errors in log

**Codenvy version:** 5.3.0

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Change rsync scripts to save real ownership instead of setting it
to current user in container.
Change rsync scripts to save all permissions instead of
executabililty only.
Add a lot of comments to describe why such rsync options are used.
Improve rsync over ssh host key checking to not add useless entries
into hosts file.

### What issues does this PR fix or reference?
Fixes #1814 
Fixes #1820 

#### Changelog
Changed rsync scripts to save true ownership.
Changed rsync scripts to set all permissions.
Improved rsync over ssh host key checking.

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by garagatyi** [comment]
@codenvy/pm Please review

File: dockerfiles/init/modules/codenvy/templates/rsyncbackup.sh.erb [hunk 1]
```diff
@@ -25,16 +21,63 @@ if [[ $(stat -c %a /opt/rsync_key) != 600 ]]; then
...
+SSH_OPTIONS+=" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
+# Set SSH logging level to make it possible to investigate problems
+SSH_OPTIONS+=" -o LogLevel=${SSH_LOG_LEVEL}"
+#######################
+
+# We need root permissions in target container to change ownership of files.
+# If user in that container has access to sudo we use it.
+# Otherwise we use rsync without sudo and if it is possible ownership will be changed.
 RSYNC_COMMAND=$(ssh ${SSH_OPTIONS} ${SRC_HOST} \
             "if hash sudo 2>/dev/null;then echo 'sudo rsync';else echo 'rsync';fi")
```
Comment (skryzhny) [inline dockerfiles/init/modules/codenvy/templates/rsyncbackup.sh.erb]: For better readability place spaces between commands

File: dockerfiles/init/modules/codenvy/templates/rsyncrestore.sh.erb [hunk 2]
```diff
@@ -10,33 +8,76 @@ DST_USR_ID=${5}
...
+##### Rsync options #####
+RSYNC_OPTIONS=""
+RSYNC_OPTIONS+=" --quiet"
+RSYNC_OPTIONS+=" --recursive"
+# Throughput limit for rsync
+RSYNC_OPTIONS+=" --bwlimit=${RSYNC_RESTORE_BWLIMIT}"
+# Sync modification timestamps to optimise transfer of not modified files.
+RSYNC_OPTIONS+=" --times"
+# Do not remove partially transferred files if transfer is interrupted. Make subsequent transfers faster.
+RSYNC_OPTIONS+=" --partial"
```
Comment (skryzhny) [inline dockerfiles/init/modules/codenvy/templates/rsyncrestore.sh.erb]: I think we would fail and remove container if first transfer failed, so it useless to add this switch

Comment (garagatyi) [inline dockerfiles/init/modules/codenvy/templates/rsyncrestore.sh.erb]: yep, I'll remove it

File: dockerfiles/init/modules/codenvy/templates/rsyncbackup.sh.erb (hunk 1 above)
Comment (garagatyi) [inline dockerfiles/init/modules/codenvy/templates/rsyncbackup.sh.erb]: ok

**Comment by garagatyi** [comment]
@skryzhny I updated PR
