### PR TITLE
Don't backup workspace if restore is failed

### LINKED ISSUE #1663: Launch backup of workspaces should be disabled if restoration of workspace was failed
Analysing logs from https://github.com/codenvy/codenvy/issues/1662 I found that:
After we failed to restore projects from backup we still trying to synchronize projects back to backup storage.
This may lead to situation when we effectively erasing backup.
Possible steps:
- Start workspace
- Restoration job failed  - /projects in BAD, inconsistent state.
- Stop of workspace
- Backup procedure starts to synchronise /projects. So GOOD backup from backup storage is replaced with BAD one from workspace

**We should not launch backup procedure if previous restoration procedure was failed.**
Maybe we need to have separate API method that removes workspace without attempting to backup projects.

**Reproduction Steps:**
Don't know

**Codenvy version:**   5.1.2

### PR DESCRIPTION
**Pull request by evoevodin**
### What does this PR do?

Fixes #1663.
If _unbindWorkspace_ is called before _bindWorkspace_ completed or called,
then warning is logged and unbind(backup) is not performed. So basically
if workspace start is failed or interrupted no one overrides old binaries.

#### Changelog
Ensures workspaces are properly backed up even if a subsequent workspace start fails.

#### Release Notes
N/A for bugs

#### Docs PR
N/A for bugs

### CODE REVIEW

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java [hunk 1]
```diff
@@ -51,6 +52,10 @@
     private final String                         nodeHost;
     private final String                         nodeIp;
 
+    private volatile boolean isBound;
```
Comment (vzhukovskii) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java]: What about using an enum here instead of operating with boolean flags?

Comment (garagatyi) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java]: This is definitely flag. Can you elaborate on what are the pros in usage of enum here?

Comment (evoevodin) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java]: This is not something exposed outside and needed for a single method, so i would stick to current approach

Comment (vzhukovskii) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java]: It won't be exposed as API. Operating with one enumerated status variable will be better for code readability and understanding. And in the same time it will reduce mistakes made in future. And what about cohesion, those two methods will be connected using one variable instead of three.

Comment (evoevodin) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java]: i've just changed the logic to use a single flag, so keep calm, nothing to argue about

Comment (vzhukovskii) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java]: Okay, I see, question has been resolved with it, thanks.

Comment (evoevodin) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java]: But yes, enum based implementation would be better i think

**Comment by evoevodin** [comment]
@bmicklea can you please verify that changelog is okay

**Comment by evoevodin** [comment]
@JamesDrummond can you please verify that the changelog is okay

**Comment by evoevodin** [comment]
Thank you
