### PR TITLE
Fix #1495 by not requiring ifconfig alias to start codenvy on Mac/Win

### LINKED ISSUE #1495: Running Codenvy in Docker: Workspace Agent Not Responding
After starting Codenvy in Docker and loading a workspace, I get the error "Workspace Agent Not Responding: Workspace agent is no longer responding. To fix the problem, verify you have a good network connection and restart the workspace." Previously, the message didn't mention network connection, only after restarting the computer. There were also messages about "OOM" in the log prior to restart, but not occurring after.

**Reproduction Steps:**
1. Ran docker: 
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}/dockerprojects/codenvy/data:/data codenvy/cli:nightly start`
2. Accepted terms when prompted in install.
3. Install completed, logged in as admin.
4. Created new user, logged out.
5. Logged in as new user, created workspace based on workspace export from codenvy.io
6. Ran workspace, error occurs when workspace attempts starting REST API.

**Codenvy version:**    5.1.0-SNAPSHOT

**OS and version:**    MacOS 10.11.6 (El Capitan)

**Docker version:** 1.12.5   

**Codenvy cli.log output:**  
```
Sat Jan  7 01:37:12 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version and network checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
DEBUG: is_initialized
/usr/bin/curl  "-s https://hub.docker.com/v2/repositories/codenvy/cli/tags/nightly/"
DEBUG: cli_parse
DEBUG: cmd_start
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
DEBUG: is_initialized
DEBUG: is_initialized
WARN: (codenvy init): 'nightly' installations cannot be upgraded to non-nightly versions
INFO: (codenvy cli): Checking registry for version 'nightly' images
eval IMAGE_HAPROXY=haproxy:1.5.18-alpine
eval IMAGE_NGINX=nginx:1.10-alpine
eval IMAGE_SWARM=swarm:1.2.5
eval IMAGE_REGISTRY=registry:2.5.0
eval IMAGE_POSTGRES=postgres:9.5.4
eval IMAGE_COMPOSE=docker/compose:1.8.1
eval IMAGE_ZOOKEEPER=zookeeper:3.4.9
eval IMAGE_SOCAT=codenvy/socat:nightly
eval IMAGE_INIT=codenvy/init:nightly
eval IMAGE_AGENTS=codenvy/agents:nightly
eval IMAGE_CODENVY=codenvy/codenvy:nightly
eval IMAGE_RSYSLOG=codenvy/rsyslog:nightly
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'haproxy:1.5.18-alpine'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'nginx:1.10-alpine'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'swarm:1.2.5'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'registry:2.5.0'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'postgres:9.5.4'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'docker/compose:1.8.1'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'zookeeper:3.4.9'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'codenvy/socat:nightly'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'codenvy/init:nightly'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'codenvy/agents:nightly'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'codenvy/codenvy:nightly'...
found
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (codenvy download): Checking for image 'codenvy/rsyslog:nightly'...
found
INFO:  
INFO: (codenvy init):  Do you accept the Codenvy license? (https://codenvy.com/legal/fair-source/)


INFO: (codenvy init):  Installing configuration and bootstrap variables:
mkdir -p "/data"
mkdir -p "/data/instance"
DEBUG: docker_run
INFO: (codenvy init):    CODENVY_HOST=192.168.65.2
INFO: (codenvy init):    CODENVY_VERSION=nightly
INFO: (codenvy init):    CODENVY_CONFIG=/Users/along/dockerprojects/codenvy/data
INFO: (codenvy init):    CODENVY_INSTANCE=/Users/along/dockerprojects/codenvy/data/instance
INFO: (codenvy cli):  Checking registry for version 'nightly' images
eval IMAGE_HAPROXY=haproxy:1.5.18-alpine
eval IMAGE_NGINX=nginx:1.10-alpine
eval IMAGE_SWARM=swarm:1.2.5
eval IMAGE_REGISTRY=registry:2.5.0
eval IMAGE_POSTGRES=postgres:9.5.4
eval IMAGE_COMPOSE=docker/compose:1.8.1
eval IMAGE_ZOOKEEPER=zookeeper:3.4.9
eval IMAGE_SOCAT=codenvy/socat:nightly
eval IMAGE_INIT=codenvy/init:nightly
eval IMAGE_AGENTS=codenvy/agents:nightly
eval IMAGE_CODENVY=codenvy/codenvy:nightly
eval IMAGE_RSYSLOG=codenvy/rsyslog:nightly
INFO: (codenvy config):  Generating codenvy configuration...
DEBUG: generate_configuration_with_puppet
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
docker_run                   --env-file="/data/codenvy.env"                   --env-file=/version/nightly/images                   -v "/Users/along/dockerprojects/codenvy/data/instance":/opt/codenvy:rw                                      -e "POSTGRES_ENV_FILE=/Users/along/dockerprojects/codenvy/data/instance/config/postgres/postgres.env"                   -e "CODENVY_ENV_FILE=/Users/along/dockerprojects/codenvy/data/instance/config/codenvy/codenvy.env"                   -e "CHE_CONTAINER_ROOT=/data"                   -e "CHE_ENVIRONMENT=production"                   -e "CHE_CONFIG=/Users/along/dockerprojects/codenvy/data/instance"                   -e "CHE_INSTANCE=/Users/along/dockerprojects/codenvy/data/instance"                   -e "CHE_REPO=off"                   --entrypoint=/usr/bin/puppet                       codenvy/init:nightly                           apply --modulepath                                 /etc/puppet/modules/                                 /etc/puppet/manifests/codenvy.pp --show_diff >> "/data/cli.log"
DEBUG: docker_run
[mNotice: Compiled catalog for 18c56430dd44.local in environment production in 0.66 seconds[0m
[mNotice: /Stage[main]/Base/File[/opt/codenvy/data]/ensure: created[0m
[mNotice: /Stage[main]/Base/File[/opt/codenvy/config]/ensure: created[0m
[mNotice: /Stage[main]/Base/File[/opt/codenvy/logs]/ensure: created[0m
[mNotice: /Stage[main]/Haproxy/File[/opt/codenvy/config/haproxy]/ensure: created[0m
[mNotice: /Stage[main]/Haproxy/File[/opt/codenvy/config/haproxy/haproxy.cfg]/ensure: defined content as '{md5}ed3e9687d7055487db7b7d1476c61d11'[0m
[mNotice: /Stage[main]/Haproxy/File[/opt/codenvy/config/haproxy/maintenance.html]/ensure: defined content as '{md5}47534e2a73dfd698f919e8649fbe51e2'[0m
[mNotice: /Stage[main]/Nginx/File[/opt/codenvy/config/nginx]/ensure: created[0m
[mNotice: /Stage[main]/Nginx/File[/opt/codenvy/config/nginx/nginx.conf]/ensure: defined content as '{md5}97a0909805156d662fe6cc2b3987575f'[0m
[mNotice: /Stage[main]/Postgres/File[/opt/codenvy/config/postgres]/ensure: created[0m
[mNotice: /Stage[main]/Postgres/File[/opt/codenvy/config/postgres/postgresql.conf]/ensure: defined content as '{md5}18be4409cc8b109314c8e8a8fd1ff86f'[0m
[mNotice: /Stage[main]/Postgres/File[/opt/codenvy/config/postgres/postgres.env]/ensure: defined content as '{md5}815726f095a7d112897d37d6611941ee'[0m
[mNotice: /Stage[main]/Swarm/File[/opt/codenvy/config/swarm]/ensure: created[0m
[mNotice: /Stage[main]/Swarm/File[/opt/codenvy/config/swarm/node_list]/ensure: defined content as '{md5}948007f928eb66e8c630f39fb05c615f'[0m
[mNotice: /Stage[main]/Registry/File[/opt/codenvy/config/registry]/ensure: created[0m
[mNotice: /Stage[main]/Registry/File[/opt/codenvy/config/registry/config.yml]/ensure: defined content as '{md5}9ce2881a150def983614c81282df29f9'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/]/ensure: created[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf]/ensure: created[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/ssh]/ensure: created[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/logback]/ensure: created[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/license]/ensure: created[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/server.xml]/ensure: defined content as '{md5}00319ae6a5d43ccec4fa03e3738b5e0c'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/codenvy.env]/ensure: defined content as '{md5}a2c164e524494033fee87c499facec52'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/oauth.properties]/ensure: defined content as '{md5}f65bef1ec3947d1b1b673c53dc1b5988'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/email-connection.properties]/ensure: defined content as '{md5}d8fc2f22fe9780f69e3308cb6826750c'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/email.properties]/ensure: defined content as '{md5}b0f4d0e0414c4e6abd5b0028e786b7be'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/logback/logback-additional-appenders.xml]/ensure: defined content as '{md5}f55efcc20c4a8c524c323d4831181ffb'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/general.properties]/ensure: defined content as '{md5}77ecf2cd9eff2d4a346cd51277c9986a'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/billing.properties]/ensure: defined content as '{md5}b4d2757361d63d8a3be13e23ce271dd1'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/metrics.properties]/ensure: defined content as '{md5}e4a4ba9f02406b0b55218ef81743ea11'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/everrest.properties]/ensure: defined content as '{md5}dc2d611d1df898e9f95bb78bdc771371'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/machine.properties]/ensure: defined content as '{md5}a39395301f51d4932f6c8658d9a8af6b'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/license.properties]/ensure: defined content as '{md5}9c493397c25fcd38e3fa828e216ee2f7'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/admin.properties]/ensure: defined content as '{md5}a1b947c4a0a4d1e629bebdc74d1d8d73'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/report.properties]/ensure: defined content as '{md5}79cab3588664e7753721c2079219108e'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/ldap.properties]/ensure: defined content as '{md5}841ca04fc0be9fcc4768ed5dd9dfe92d'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/rsyncbackup.sh]/ensure: defined content as '{md5}b435f2e7b82bb45d29d7568d9ac77f7d'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/rsyncrestore.sh]/ensure: defined content as '{md5}7ff71363ed2341ec20fda1adbadafede'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/add-node.sh]/ensure: defined content as '{md5}356a09f9d4def49192ff1dbeaa8a63d6'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/jmxremote.access]/ensure: defined content as '{md5}a951b5b6624cad3b0ec555c40d624a9c'[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/jmxremote.password]/ensure: defined content as '{md5}cb05d0ae49d28c22a21ccc874c6688c6'[0m
[mNotice: /Stage[main]/Codenvy/Exec[generate_ssh_key]/returns: executed successfully[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/cleanUpWorkspaceStorage.sh]/ensure: defined content as '{md5}4cd140e8dde3e86703719062e82ec454'[0m
[mNotice: /Stage[main]/Rsyslog/File[/opt/codenvy/config/rsyslog]/ensure: created[0m
[mNotice: /Stage[main]/Rsyslog/File[/opt/codenvy/config/rsyslog/rsyslog.conf]/ensure: defined content as '{md5}78b6c428785475d9f632a571c9755c45'[0m
[mNotice: /Stage[main]/Rsyslog/File[/opt/codenvy/config/rsyslog/haproxy.conf]/ensure: defined content as '{md5}386dca312192c0fd0d1a0cff7a020645'[0m
[mNotice: /Stage[main]/Rsyslog/File[/opt/codenvy/config/rsyslog/swarm.conf]/ensure: defined content as '{md5}6dbeaf8e77ab5cc3e3f8d2b99a46477c'[0m
[mNotice: /Stage[main]/Rsyslog/File[/opt/codenvy/config/rsyslog/zookeeper.conf]/ensure: defined content as '{md5}4a340beef2378bdaccef09b273f2a713'[0m
[mNotice: /Stage[main]/Rsyslog/File[/opt/codenvy/config/rsyslog/registry.conf]/ensure: defined content as '{md5}cce8b52c5b9b52e61306f85b5df5a18c'[0m
[mNotice: /Stage[main]/Lighttpd/File[/opt/codenvy/config/lighttpd]/ensure: created[0m
[mNotice: /Stage[main]/Lighttpd/File[/opt/codenvy/config/lighttpd/lighttpd.conf]/ensure: defined content as '{md5}df36baf11e4da58f17dd9ef0e8ca8bcc'[0m
[mNotice: /Stage[main]/Compose/Compose::Generate_compose_file[docker-compose-container.yml]/File[/opt/codenvy/docker-compose-container.yml]/ensure: defined content as '{md5}8babef6a7160e5ce58ad6244c5ed0577'[0m
[mNotice: /Stage[main]/Compose/Compose::Generate_compose_file[docker-compose.yml]/File[/opt/codenvy/docker-compose.yml]/ensure: defined content as '{md5}a5c430b5b33b54d9abf58614bf2877f0'[0m
[mNotice: Applied catalog in 0.69 seconds[0m
INFO: (codenvy config):  Customizing docker-compose for running in a container
DEBUG: has_docker_for_windows_client
INFO: (codenvy start):  Preflight checks
DEBUG: port_open
         port 80 (http):        [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 443 (https):      [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 2181 (zookeeper): [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 5000 (registry):  [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 23750 (socat):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 23751 (swarm):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 32001 (Codenvy JMX):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 32101 (Codenvy JMX):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open

INFO: (codenvy start):  Starting containers...
docker_compose --file="/data/instance/docker-compose-container.yml" -p="codenvy" up -d >> "/data/cli.log" 2>&1
DEBUG: docker_compose
DEBUG: docker_run
Creating codenvy_rsyslog_1
Creating codenvy_socat_1
Creating codenvy_nginx_1
Creating codenvy_agents_1
Creating codenvy_postgres_1
Creating codenvy_registry_1
Creating codenvy_zookeeper_1
Creating codenvy_swarm_1
Creating codenvy_haproxy_1
Creating codenvy_codenvy_1
docker inspect -f '{{.Id}}' codenvy_codenvy_1
INFO: (codenvy start):  Services booting...
INFO: (codenvy start):  Server logs at "docker logs -f codenvy_codenvy_1"
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker restart codenvy_haproxy_1 >> "/data/cli.log" 2>&1
codenvy_haproxy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker restart codenvy_haproxy_1 >> "/data/cli.log" 2>&1
codenvy_haproxy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker restart codenvy_haproxy_1 >> "/data/cli.log" 2>&1
codenvy_haproxy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker restart codenvy_haproxy_1 >> "/data/cli.log" 2>&1
codenvy_haproxy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker restart codenvy_haproxy_1 >> "/data/cli.log" 2>&1
codenvy_haproxy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker restart codenvy_haproxy_1 >> "/data/cli.log" 2>&1
codenvy_haproxy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker restart codenvy_haproxy_1 >> "/data/cli.log" 2>&1
codenvy_haproxy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
200
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
200
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
INFO: (codenvy start):  Booted and reachable
DEBUG: is_initialized
INFO: (codenvy start):  Ver: nightly
INFO: (codenvy start):  Use: http://localhost
INFO: (codenvy start):  API: http://localhost/swagger
Sat Jan  7 01:49:01 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version and network checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
DEBUG: is_initialized
DEBUG: is_initialized
DEBUG: is_initialized
/usr/bin/curl  "-s https://hub.docker.com/v2/repositories/codenvy/cli/tags/nightly/"
DEBUG: cli_parse
DEBUG: cmd_start
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker inspect -f '{{.Id}}' codenvy_codenvy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
200
INFO: (codenvy start): Codenvy is already running
INFO: (codenvy start): Server logs at "docker logs -f codenvy_codenvy_1"
DEBUG: is_initialized
INFO: (codenvy start): Ver: nightly
INFO: (codenvy start): Use: http://localhost
INFO: (codenvy start): API: http://localhost/swagger
Sat Jan  7 01:59:46 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version and network checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
DEBUG: is_initialized
DEBUG: is_initialized
DEBUG: is_initialized
/usr/bin/curl  "-s https://hub.docker.com/v2/repositories/codenvy/cli/tags/nightly/"
DEBUG: cli_parse
DEBUG: cmd_restart
INFO: (codenvy restart): Restarting...
DEBUG: cmd_stop
INFO: (codenvy stop): Stopping containers...
DEBUG: is_initialized
docker_compose --file="/data/instance/docker-compose-container.yml" -p=codenvy stop -t 180 >> "/data/cli.log" 2>&1 || true
DEBUG: docker_compose
DEBUG: docker_run
Stopping codenvy_codenvy_1 ... 
Stopping codenvy_haproxy_1 ... 
Stopping codenvy_zookeeper_1 ... 
Stopping codenvy_swarm_1 ... 
Stopping codenvy_registry_1 ... 
Stopping codenvy_postgres_1 ... 
Stopping codenvy_socat_1 ... 
Stopping codenvy_agents_1 ... 
Stopping codenvy_nginx_1 ... 
Stopping codenvy_rsyslog_1 ... 
[6A[2K
Stopping codenvy_registry_1 ... done
[6B[8A[2K
Stopping codenvy_zookeeper_1 ... done
[8B[10A[2K
Stopping codenvy_codenvy_1 ... done
[10B[5A[2K
Stopping codenvy_postgres_1 ... done
[5B[9A[2K
Stopping codenvy_haproxy_1 ... done
[9B[7A[2K
Stopping codenvy_swarm_1 ... done
[7B[3A[2K
Stopping codenvy_agents_1 ... done
[3B[2A[2K
Stopping codenvy_nginx_1 ... done
[2B[4A[2K
Stopping codenvy_socat_1 ... done
[4B[1A[2K
Stopping codenvy_rsyslog_1 ... done
[1BINFO: (codenvy stop): Removing containers...
docker_compose --file="/data/instance/docker-compose-container.yml" -p=codenvy rm >> "/data/cli.log" 2>&1 || true
DEBUG: docker_compose
DEBUG: docker_run
Going to remove codenvy_codenvy_1, codenvy_haproxy_1, codenvy_zookeeper_1, codenvy_swarm_1, codenvy_registry_1, codenvy_postgres_1, codenvy_socat_1, codenvy_agents_1, codenvy_nginx_1, codenvy_rsyslog_1
Removing codenvy_codenvy_1 ... 
Removing codenvy_haproxy_1 ... 
Removing codenvy_zookeeper_1 ... 
Removing codenvy_swarm_1 ... 
Removing codenvy_registry_1 ... 
Removing codenvy_postgres_1 ... 
Removing codenvy_socat_1 ... 
Removing codenvy_agents_1 ... 
Removing codenvy_nginx_1 ... 
Removing codenvy_rsyslog_1 ... 
[7A[2K
Removing codenvy_swarm_1 ... done
[7B[2A[2K
Removing codenvy_nginx_1 ... done
[2B[3A[2K
Removing codenvy_agents_1 ... done
[3B[8A[2K
Removing codenvy_zookeeper_1 ... done
[8B[10A[2K
Removing codenvy_codenvy_1 ... done
[10B[6A[2K
Removing codenvy_registry_1 ... done
[6B[9A[2K
Removing codenvy_haproxy_1 ... done
[9B[4A[2K
Removing codenvy_socat_1 ... done
[4B[5A[2K
Removing codenvy_postgres_1 ... done
[5B[1A[2K
Removing codenvy_rsyslog_1 ... done
[1BDEBUG: cmd_start
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
DEBUG: is_initialized
INFO: (codenvy cli): Checking registry for version 'nightly' images
eval IMAGE_HAPROXY=haproxy:1.5.18-alpine
eval IMAGE_NGINX=nginx:1.10-alpine
eval IMAGE_SWARM=swarm:1.2.5
eval IMAGE_REGISTRY=registry:2.5.0
eval IMAGE_POSTGRES=postgres:9.5.4
eval IMAGE_COMPOSE=docker/compose:1.8.1
eval IMAGE_ZOOKEEPER=zookeeper:3.4.9
eval IMAGE_SOCAT=codenvy/socat:nightly
eval IMAGE_INIT=codenvy/init:nightly
eval IMAGE_AGENTS=codenvy/agents:nightly
eval IMAGE_CODENVY=codenvy/codenvy:nightly
eval IMAGE_RSYSLOG=codenvy/rsyslog:nightly
INFO: (codenvy config):  Generating codenvy configuration...
DEBUG: generate_configuration_with_puppet
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
docker_run                   --env-file="/data/codenvy.env"                   --env-file=/version/nightly/images                   -v "/Users/along/dockerprojects/codenvy/data/instance":/opt/codenvy:rw                                      -e "POSTGRES_ENV_FILE=/Users/along/dockerprojects/codenvy/data/instance/config/postgres/postgres.env"                   -e "CODENVY_ENV_FILE=/Users/along/dockerprojects/codenvy/data/instance/config/codenvy/codenvy.env"                   -e "CHE_CONTAINER_ROOT=/data"                   -e "CHE_ENVIRONMENT=production"                   -e "CHE_CONFIG=/Users/along/dockerprojects/codenvy/data/instance"                   -e "CHE_INSTANCE=/Users/along/dockerprojects/codenvy/data/instance"                   -e "CHE_REPO=off"                   --entrypoint=/usr/bin/puppet                       codenvy/init:nightly                           apply --modulepath                                 /etc/puppet/modules/                                 /etc/puppet/manifests/codenvy.pp --show_diff >> "/data/cli.log"
DEBUG: docker_run
[mNotice: Compiled catalog for b4cd0873c0e7.local in environment production in 0.73 seconds[0m
[mNotice: Applied catalog in 0.32 seconds[0m
INFO: (codenvy config):  Customizing docker-compose for running in a container
DEBUG: has_docker_for_windows_client
INFO: (codenvy start):  Preflight checks
DEBUG: port_open
         port 80 (http):        [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 443 (https):      [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 2181 (zookeeper): [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 5000 (registry):  [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 23750 (socat):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 23751 (swarm):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 32001 (Codenvy JMX):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 32101 (Codenvy JMX):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open

INFO: (codenvy start):  Starting containers...
docker_compose --file="/data/instance/docker-compose-container.yml" -p="codenvy" up -d >> "/data/cli.log" 2>&1
DEBUG: docker_compose
DEBUG: docker_run
Creating codenvy_nginx_1
Creating codenvy_agents_1
Creating codenvy_rsyslog_1
Creating codenvy_socat_1
Creating codenvy_postgres_1
Creating codenvy_registry_1
Creating codenvy_zookeeper_1
Creating codenvy_swarm_1
Creating codenvy_haproxy_1
Creating codenvy_codenvy_1
docker inspect -f '{{.Id}}' codenvy_codenvy_1
INFO: (codenvy start):  Services booting...
INFO: (codenvy start):  Server logs at "docker logs -f codenvy_codenvy_1"
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker restart codenvy_haproxy_1 >> "/data/cli.log" 2>&1
codenvy_haproxy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
200
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
200
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
INFO: (codenvy start):  Booted and reachable
DEBUG: is_initialized
INFO: (codenvy start):  Ver: nightly
INFO: (codenvy start):  Use: http://localhost
INFO: (codenvy start):  API: http://localhost/swagger
Sat Jan  7 02:15:17 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version and network checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
DEBUG: is_initialized
DEBUG: is_initialized
DEBUG: is_initialized
/usr/bin/curl  "-s https://hub.docker.com/v2/repositories/codenvy/cli/tags/nightly/"
DEBUG: cli_parse
DEBUG: cmd_stop
INFO: (codenvy stop): Stopping containers...
DEBUG: is_initialized
docker_compose --file="/data/instance/docker-compose-container.yml" -p=codenvy stop -t 180 >> "/data/cli.log" 2>&1 || true
DEBUG: docker_compose
DEBUG: docker_run
Stopping codenvy_codenvy_1 ... 
Stopping codenvy_haproxy_1 ... 
Stopping codenvy_swarm_1 ... 
Stopping codenvy_zookeeper_1 ... 
Stopping codenvy_registry_1 ... 
Stopping codenvy_postgres_1 ... 
Stopping codenvy_socat_1 ... 
Stopping codenvy_agents_1 ... 
Stopping codenvy_rsyslog_1 ... 
Stopping codenvy_nginx_1 ... 
[6A[2K
Stopping codenvy_registry_1 ... done
[6B[7A[2K
Stopping codenvy_zookeeper_1 ... done
[7B[10A[2K
Stopping codenvy_codenvy_1 ... done
[10B[5A[2K
Stopping codenvy_postgres_1 ... done
[5B[8A[2K
Stopping codenvy_swarm_1 ... done
[8B[9A[2K
Stopping codenvy_haproxy_1 ... done
[9B[4A[2K
Stopping codenvy_socat_1 ... done
[4B[3A[2K
Stopping codenvy_agents_1 ... done
[3B[1A[2K
Stopping codenvy_nginx_1 ... done
[1B[2A[2K
Stopping codenvy_rsyslog_1 ... done
[2BINFO: (codenvy stop): Removing containers...
docker_compose --file="/data/instance/docker-compose-container.yml" -p=codenvy rm >> "/data/cli.log" 2>&1 || true
DEBUG: docker_compose
DEBUG: docker_run
Going to remove codenvy_codenvy_1, codenvy_haproxy_1, codenvy_swarm_1, codenvy_zookeeper_1, codenvy_registry_1, codenvy_postgres_1, codenvy_socat_1, codenvy_agents_1, codenvy_rsyslog_1, codenvy_nginx_1
Removing codenvy_codenvy_1 ... 
Removing codenvy_haproxy_1 ... 
Removing codenvy_swarm_1 ... 
Removing codenvy_zookeeper_1 ... 
Removing codenvy_registry_1 ... 
Removing codenvy_postgres_1 ... 
Removing codenvy_socat_1 ... 
Removing codenvy_agents_1 ... 
Removing codenvy_rsyslog_1 ... 
Removing codenvy_nginx_1 ... 
[4A[2K
Removing codenvy_socat_1 ... done
[4B[3A[2K
Removing codenvy_agents_1 ... done
[3B[9A[2K
Removing codenvy_haproxy_1 ... done
[9B[5A[2K
Removing codenvy_postgres_1 ... done
[5B[10A[2K
Removing codenvy_codenvy_1 ... done
[10B[8A[2K
Removing codenvy_swarm_1 ... done
[8B[6A[2K
Removing codenvy_registry_1 ... done
[6B[2A[2K
Removing codenvy_rsyslog_1 ... done
[2B[7A[2K
Removing codenvy_zookeeper_1 ... done
[7B[1A[2K
Removing codenvy_nginx_1 ... done
[1BMon Jan  9 15:36:20 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version and network checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
DEBUG: is_initialized
DEBUG: is_initialized
DEBUG: is_initialized
/usr/bin/curl  "-s https://hub.docker.com/v2/repositories/codenvy/cli/tags/nightly/"
WARN: There is a newer codenvy/cli:nightly image on DockerHub.
DEBUG: cli_parse
DEBUG: cmd_start
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
DEBUG: is_initialized
INFO: (codenvy cli): Checking registry for version 'nightly' images
eval IMAGE_HAPROXY=haproxy:1.5.18-alpine
eval IMAGE_NGINX=nginx:1.10-alpine
eval IMAGE_SWARM=swarm:1.2.5
eval IMAGE_REGISTRY=registry:2.5.0
eval IMAGE_POSTGRES=postgres:9.5.4
eval IMAGE_COMPOSE=docker/compose:1.8.1
eval IMAGE_ZOOKEEPER=zookeeper:3.4.9
eval IMAGE_SOCAT=codenvy/socat:nightly
eval IMAGE_INIT=codenvy/init:nightly
eval IMAGE_AGENTS=codenvy/agents:nightly
eval IMAGE_CODENVY=codenvy/codenvy:nightly
eval IMAGE_RSYSLOG=codenvy/rsyslog:nightly
INFO: (codenvy config):  Generating codenvy configuration...
DEBUG: generate_configuration_with_puppet
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
docker_run                   --env-file="/data/codenvy.env"                   --env-file=/version/nightly/images                   -v "/Users/along/dockerprojects/codenvy/data/instance":/opt/codenvy:rw                                      -e "POSTGRES_ENV_FILE=/Users/along/dockerprojects/codenvy/data/instance/config/postgres/postgres.env"                   -e "CODENVY_ENV_FILE=/Users/along/dockerprojects/codenvy/data/instance/config/codenvy/codenvy.env"                   -e "CHE_CONTAINER_ROOT=/data"                   -e "CHE_ENVIRONMENT=production"                   -e "CHE_CONFIG=/Users/along/dockerprojects/codenvy/data/instance"                   -e "CHE_INSTANCE=/Users/along/dockerprojects/codenvy/data/instance"                   -e "CHE_REPO=off"                   --entrypoint=/usr/bin/puppet                       codenvy/init:nightly                           apply --modulepath                                 /etc/puppet/modules/                                 /etc/puppet/manifests/codenvy.pp --show_diff >> "/data/cli.log"
DEBUG: docker_run
[mNotice: Compiled catalog for d65ce34dcda3.local in environment production in 0.63 seconds[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/general.properties]/content: 
--- /opt/codenvy/config/codenvy/conf/general.properties
+++ /tmp/puppet-file20170109-1-1s87mnr
@@ -32,11 +32,11 @@
 
 # Limits
 limits.user.workspaces.count=30
-limits.user.workspaces.run.count=60
+limits.user.workspaces.run.count=10
 limits.user.workspaces.ram=100gb
 limits.organization.workspaces.ram=100gb
 limits.organization.workspaces.count=30
-limits.organization.workspaces.run.count=60
+limits.organization.workspaces.run.count=10
 limits.workspace.env.ram=16gb
 limits.workspace.start.throughput=5
 
[0m
[mNotice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/general.properties]/content: content changed '{md5}69a19320e5728395f3bbd72d09c11844' to '{md5}77ecf2cd9eff2d4a346cd51277c9986a'[0m
[mNotice: Applied catalog in 0.34 seconds[0m
INFO: (codenvy config):  Customizing docker-compose for running in a container
DEBUG: has_docker_for_windows_client
INFO: (codenvy start):  Preflight checks
DEBUG: port_open
         port 80 (http):        [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 443 (https):      [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 2181 (zookeeper): [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 5000 (registry):  [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 23750 (socat):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 23751 (swarm):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 32001 (Codenvy JMX):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 32101 (Codenvy JMX):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open

INFO: (codenvy start):  Starting containers...
docker_compose --file="/data/instance/docker-compose-container.yml" -p="codenvy" up -d >> "/data/cli.log" 2>&1
DEBUG: docker_compose
DEBUG: docker_run
Creating codenvy_socat_1
Creating codenvy_nginx_1
Creating codenvy_agents_1
Creating codenvy_postgres_1
Creating codenvy_rsyslog_1
Creating codenvy_zookeeper_1
Creating codenvy_swarm_1
Creating codenvy_registry_1
Creating codenvy_haproxy_1
Creating codenvy_codenvy_1
docker inspect -f '{{.Id}}' codenvy_codenvy_1
INFO: (codenvy start):  Services booting...
INFO: (codenvy start):  Server logs at "docker logs -f codenvy_codenvy_1"
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: has_docker_for_windows_client
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
docker restart codenvy_haproxy_1 >> "/data/cli.log" 2>&1
codenvy_haproxy_1
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
200
/usr/bin/curl  "-I -k 192.168.65.2/api/ -s -o /dev/null --write-out %{http_code}"
200
DEBUG: is_docker_for_mac
DEBUG: has_docker_for_windows_client
INFO: (codenvy start):  Booted and reachable
DEBUG: is_initialized
INFO: (codenvy start):  Ver: nightly
INFO: (codenvy start):  Use: http://localhost
INFO: (codenvy start):  API: http://localhost/swagger`

```

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
- Add CHE_DOCKER_IP_EXTERNAL in shell script for docker for mac/docker for windows
- There is as well an ProxyTransformer on codenvy that remap the calls to docker daemon ephemeral ports through port 80 that needs to be remapped because browser can’t reach “internal docker ip” directly (for now the calls are made to the docker daemon url)
   : so handle che.docker.ip.external as well for the ProxyTransformer and handle the case of “internal” and “external” addresses like in Che. As we also need the “CHE_HOST” ip, adds this property to codenvy.env to be available inside codenvy. Rewrite as well the template to let codenvy insert the codenvy.host property at runtime (if %5$ argument is used)

### What issues does this PR fix or reference?
https://github.com/codenvy/codenvy/issues/1495

### Previous Behavior
User has to define ifconfig lo0 alias with docker ip

### New Behavior
User doesn't need anymore to use ifconfig lo0 alias

### Tests written?
Yes

### Docs requirements?
1.  User docs changes  
remove the requirement on requiring an alias on lo0

Change-Id: Ibeb23d6a96ad15b194a7571c00c174f8aaa92c87
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>

### CODE REVIEW

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/TerminalServerProxyTransformer.java [hunk 1]
```diff
@@ -24,7 +26,7 @@
  */
 public class TerminalServerProxyTransformer extends UriTemplateServerProxyTransformer {
     @Inject
-    public TerminalServerProxyTransformer(@Named("machine.proxy_terminal_server_url_template") String serverUrlTemplate) {
-        super(serverUrlTemplate);
+    public TerminalServerProxyTransformer(@Named("machine.proxy_wsagent_server_url_template") String serverUrlTemplate, @Nullable @Named("codenvy.host") String codenvyHost, @Nullable @Named("che.docker.ip.external") String externalAddress) {
```
Comment (garagatyi) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/TerminalServerProxyTransformer.java]: Looks like there is a mistake in name of property

File: dockerfiles/codenvy/entrypoint.sh [hunk 2]
```diff
@@ -40,5 +66,12 @@ COUNT=0
              fi
   done
 
+# CHE_DOCKER_IP_EXTERNAL must be set if you are in a VM.
+HOSTNAME=${CHE_DOCKER_IP_EXTERNAL:-$(get_docker_external_hostname)}
+if has_external_hostname; then
+  # Internal property used by Che to set hostname.
```
Comment (garagatyi) [inline dockerfiles/codenvy/entrypoint.sh]: Maybe Codenvy instead of Che?

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java [hunk 3]
```diff
@@ -64,21 +70,46 @@ public ServerImpl transform(ServerImpl server) {
         if (serverPath.startsWith("/")) {
             serverPath = serverPath.substring(1);
         }
-
+        final String externalAddress;
+        final String externalServerHost;
+        final String internalServerHost;
+        if (!Strings.isNullOrEmpty(externalAddressProperty) && !Strings.isNullOrEmpty(codenvyHost)) {
```
Comment (garagatyi) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java]: As far as I can see codenvyHost is set from puppet variable codenvy::host_url. @riuvshin is it always set?
If so then this variable is always non-null.

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/CodenvyDockerServerEvaluationStrategy.java [hunk 4]
```diff
@@ -41,7 +56,11 @@
 
     @Override
     protected Map<String, String> getExternalAddressesAndPorts(ContainerInfo containerInfo, String internalHost) {
-        return getInternalAddressesAndPorts(containerInfo, internalHost);
+        String externalAddress = externalAddressProperty != null ?
```
Comment (benoitf) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/CodenvyDockerServerEvaluationStrategy.java]: yes

File: dockerfiles/codenvy/entrypoint.sh [hunk 5]
```diff
@@ -40,5 +66,12 @@ COUNT=0
              fi
   done
 
+# CHE_DOCKER_IP_EXTERNAL must be set if you are in a VM.
+HOSTNAME=${CHE_DOCKER_IP_EXTERNAL:-$(get_docker_external_hostname)}
```
Comment (benoitf) [inline dockerfiles/codenvy/entrypoint.sh]: Afaik on mac it's for single node

File: dockerfiles/codenvy/entrypoint.sh (hunk 2 above)
Comment (benoitf) [inline dockerfiles/codenvy/entrypoint.sh]: Yes

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java [hunk 6]
```diff
@@ -64,21 +70,46 @@ public ServerImpl transform(ServerImpl server) {
         if (serverPath.startsWith("/")) {
             serverPath = serverPath.substring(1);
         }
-
+        final String externalAddress;
+        final String externalServerHost;
```
Comment (benoitf) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java]: Just read few lines after

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java (hunk 3 above)
Comment (benoitf) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java]: It's not set in non dockerized version ( soon removed but still there)

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/TerminalServerProxyTransformer.java (hunk 1 above)
Comment (benoitf) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/TerminalServerProxyTransformer.java]: What mistake ?

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java (hunk 6 above)
Comment (benoitf) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java]: ok

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java (hunk 3 above)
Comment (garagatyi) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java]: But in dockerized Codenvy it is always set? If so will multiple nodes of swarm work?

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/TerminalServerProxyTransformer.java (hunk 1 above)
Comment (garagatyi) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/TerminalServerProxyTransformer.java]: Terminal transformer uses rule for wsagent

Comment (benoitf) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/TerminalServerProxyTransformer.java]: ah yes it is a mistake !

File: plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java (hunk 3 above)
Comment (benoitf) [inline plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java]: yes it is always set in dockerized codenvy.
I will try if I only rewrite proxytransformer without changing CodenvyDockerServerEvaluationStrategy for handling multiple nodes of swarm (on mac/windows)

**Comment by benoitf** [comment]
@garagatyi so I rewrote part (we don't need to change CodenvyDockerServerEvaluationStrategy)
also IMHO it can handle several swarm nodes with that approach

File: dockerfiles/init/modules/codenvy/templates/machine.properties.erb [hunk 7]
```diff
@@ -64,8 +64,8 @@ che.docker.always_pull_image=true
 che.docker.api=1.20
 
 # https support
-machine.proxy_wsagent_server_url_template=<%= scope.lookupvar('codenvy::host_protocol') %>://<%= scope.lookupvar('codenvy::host_url') %>/%3$s_%2$s/%4$s
-machine.proxy_terminal_server_url_template=<%= scope.lookupvar('codenvy::host_protocol') %>://<%= scope.lookupvar('codenvy::host_url') %>/%3$s_%2$s/%4$s
+machine.proxy_wsagent_server_url_template=<%= scope.lookupvar('codenvy::host_protocol') %>://%5$s/%3$s_%2$s/%4$s
```
Comment (benoitf) [inline dockerfiles/init/modules/codenvy/templates/machine.properties.erb]: it seems you're asking me to do your job ?
https://github.com/codenvy/deployment/commit/16e7d0f0916df8c132971d15d9755da51f23f264

I will provide them but you may follow your tips as well.

Comment (garagatyi) [inline dockerfiles/init/modules/codenvy/templates/machine.properties.erb]: Yes, thank you.

**Comment by TylerJewell** [comment]
@benoitf - can you comment a little bit on the differences between this PR for Codenvy and this one from @garagatyi for Eclipse Che? https://github.com/eclipse/che/pull/3812

My primary concern here is that can we verify that after both PRs are merged that:
1. We can launch Codenvy and Che by only setting CHE_HOST or CODENVY_HOST on a hosting provider (no other properties should be set as a mandatory, only optionally).

2. That we can start codenvy on a Mac without settting the ifconfig.

3. Is there a sequence in which this PR vs. #3812 from Che needs to be merged?

**Comment by benoitf** [comment]
@TylerJewell I would say that it's not related. (so no need to have the other PR merge first of after)
This PR address the point 2.

when you start codenvy by default it will use che-ip utility and set the host to be 192.168.65.2
then API JSON links will be generated using that ip.
The issue is that the browser (with UD and IDE) will grab this link with ip and try to connect to.
While it is not possible with docker for mac as redirect of ports is done on localhost interface

so this PR do the same logic than in che, where when we detect that codenvy is started on mac, we define an external property so that it's mapped to localhost

so, a user, launching a fresh codenvy on mac/windows will have something that work by default.

File: dockerfiles/init/modules/codenvy/templates/machine.properties.erb (hunk 7 above)
Comment (benoitf) [inline dockerfiles/init/modules/codenvy/templates/machine.properties.erb]: added

**Comment by benoitf** [comment]
@garagatyi how do we progress on this pull request ? It seems all your remarks are fixed

**Comment by garagatyi** [comment]
I spend some time on analyzing what this PR changes and what impacts on a system it has.
As far as I can see it really fixes the problem.
On the other hand you changed design of UriTemplateServerProxyTransformer in a way it was not intended to be changed by original design. Also it introduces infrastructural knowledge to this class.
I see it as reducing flexibility of the system.

Please consider alternate implementation of these changes.
Make UriTemplateServerProxyTransformer use 2 patterns instead of 1. Patterns for internal & external uri transforming.
In that case CLI can transform patterns to respect OS where we run Codenvy.
This implementation of your idea doesn’t change original design of UriTemplateServerProxyTransformer, but patches it to respect recently added concept of external/internal uris. Also it doesn’t expose infrastructural information to UriTemplateServerProxyTransformer.

@benoitf  @skabashnyuk @gazarenkov WDYT?

**Comment by gazarenkov** [comment]
I'd prefer to have additional dedicated property over the dependency on existed one. 
I see it as more straightforward, the code and docs will be simpler => the solution is better maintainable and explainable.
I would recommend to change the PR this way (should be quite easy change no?) unless there are some serious missed issue which has to be more discussed.
@benoitf ?

**Comment by benoitf** [comment]
as I don't see any specification on the previous design and how it is badly documented (I was asked to document some code I didn't wrote), I don't see why there are such new requirements.
My issue is that for now the code is backward compliant with existing customer properties.
Introducing a new property will require customers to add/update new properties while it's not required.

**Comment by benoitf** [comment]
> I see it as more straightforward, the code and docs will be simpler => the solution is better maintainable and explainable. 
IMHO I'm not sure that having four properties instead of two being almost all the time the same values is being more simple.

On the documentation : here is the magic, it fixes an issue so there is no extra documentation : we can remove some pre-requisites for all mac users running codenvy on macOs

**Comment by TylerJewell** [comment]
@gazarenkov - can we break this into two pr?  Merge what we have now so that we can allow codenvy to run on Mac again as it does not now.  And if we want to refactor key properties we can do another pr and make it required for 5.2 even.

**Comment by gazarenkov** [comment]
docs - as I understand it is a matter of one clear sentence to add, so not a big issue.
for compatibility, I think since it is property adding - it should not be an issue (usually solved by default behavior if new property not present).
So, I'd still non-insistently prefer additional property option as it seems to be better maintainable but 
neither option looks significantly better than other, so, I'd let you guys either find a compromise or let decide the one who supposed to be a primary code maintainer (the one who takes responsibility for the future of this code) of the module where this class located in.

**Comment by gazarenkov** [comment]
@TylerJewell 
As I understand @garagatyi can provide his option shortly, so I'd prefer to make some decision about it once, but, if the compromise is impossible right now - let's consider your 2 steps option :)

**Comment by benoitf** [comment]
@gazarenkov it looks odd to me that the issue is there for months (since we have dockerized codenvy) and now that I provide a pull request to fix the issue, and that review has been delayed  a "can provide his option shortly" is coming around.

**Comment by garagatyi** [comment]
@benoitf @gazarenkov @skabashnyuk I created [PR](https://github.com/codenvy/codenvy/pull/1603) with alternative implementation suggested previously.
We should consider which of implementations should be merged.
